name: CD Pipeline

on:
  workflow_dispatch:
    inputs:
      ECRURL:
        description: "ECR Registry URL (with / at end)"
        required: true
        default: "081654307023.dkr.ecr.ap-south-1.amazonaws.com/"
      REPO:
        description: "Repository Name"
        required: true
        default: "wezvatechledger"
      IMAGE:
        description: "Image Tag"
        required: true
        default: "rel28"
      TEST:
        description: "Environment"
        required: true
        type: choice
        options:
          - functional
          - integration
          - regression
          - uat
          - release

jobs:
  deploy:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest

    steps:
      # -----------------------------
      # Checkout Deployment Repo
      # -----------------------------
      - name: Checkout Deployment Repo
        uses: actions/checkout@v4
        with:
          repository: wezva-fintech/ledger-deployment
          ref: main
          token: ${{ secrets.GH_PAT }}

      # -----------------------------
      # Update values.yaml
      # -----------------------------
      - name: Update Helm values
        run: |
          cd envs/${{ inputs.TEST }}

          echo "Updating image repository..."
          sed -i "s|repository:.*|repository: ${{ inputs.ECRURL }}${{ env.REPO_NAME }}|g" values.yaml

          echo "Updating image tag..."
          sed -i "s|tag:.*|tag: ${{ inputs.IMAGE }}|g" values.yaml

          echo "Updated values.yaml:"
          cat values.yaml

      # -----------------------------
      # Commit & Push Changes
      # -----------------------------
      - name: Commit and Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add .
          git commit -m "New deployment for Build ${{ inputs.IMAGE }}" || echo "No changes to commit"

          git push origin main
